import { execFile } from 'node:child_process'
import path from 'node:path'
import { promisify } from 'node:util'
import type { LoadContext, Plugin } from '@docusaurus/types'
import { injectIgnoreMarkers } from './injectIgnoreMarkers'
import { type PluginOptions, resolveOptions } from './options'
import { buildPagefindJsUrl, resolvePagefindDir } from './resolvePagefindDir';

const execFileAsync = promisify(execFile)

export default function pluginPagefind(
	context: LoadContext,
	options: PluginOptions = {},
): Plugin<void> {
	const mergedOptions = resolveOptions(options);
	const { pagefindDir, warning } = resolvePagefindDir(
		context.outDir,
		mergedOptions,
	);
	const pagefindJsUrl = buildPagefindJsUrl(
		context.siteConfig.baseUrl,
		pagefindDir,
	);

	return {
		name: 'docusaurus-plugin-pagefind',

		getThemePath() {
			// dist/theme/ — compiled JS consumed by webpack
			return path.resolve(__dirname, './theme')
		},

		getTypeScriptThemePath() {
			// src/theme/ — TypeScript source for swizzling only, NOT processed by webpack
			return path.resolve(__dirname, '../src/theme')
		},

		// /pagefind/pagefind.js is a runtime asset generated by postBuild.
		// webpack cannot bundle it, so we exclude it via externals, substituting
		// the real baseUrl/outputPath-aware URL computed above. The
		// webpackIgnore comment on the source import is not reliable in this
		// build pipeline (it can be stripped before webpack ever sees it), so
		// externals — matching on the raw import request — is the mechanism
		// that actually makes this work.
		configureWebpack() {
			return {
				externals: [
					(
						{ request }: { request?: string },
						callback: (err?: Error | null, result?: string) => void
					) => {
						if (request === '/pagefind/pagefind.js') {
							callback(
								null,
								`promise import(${JSON.stringify(pagefindJsUrl)})`,
							);
							return;
						}
						callback()
					}
				]
			}
		},

		async postBuild({ outDir }) {
			if (warning) {
				console.warn(warning);
			}
			if (mergedOptions.excludeGlobs && mergedOptions.excludeGlobs.length > 0) {
				await injectIgnoreMarkers(outDir, mergedOptions.excludeGlobs)
			}
			// The ESM-only pagefind package cannot be import()ed from plugin code:
			// Docusaurus loads plugins through jiti, whose CJS transform/sandbox
			// breaks both plain dynamic import() and the new-Function escape hatch.
			// Run the indexing step in a plain Node child process instead, where
			// native import() just works (see pagefindWorker.mts).
			await execFileAsync(process.execPath, [
				path.join(__dirname, 'pagefindWorker.mjs'),
				JSON.stringify({ outDir, options: mergedOptions })
			])
		}
	}
}

export type { PluginOptions } from './options'
